### ISSUE TITLE
Revisite database design

### ISSUE THREAD

**Issue by EvilAngel94** [EvilAngel94/RecipeCookBook#11]
**Description**
The first has a misstake in it. As a recipe has mutliple ingredients and multiple steps, it is necessary that there is an extra (2) tables to connect the steps with the recipe as well as ingredients with recipe. 

In the attachement you can find a scetch of the new implementation.

**TODO**
- [x] adjust the current design
- [x] create new SQL script
- [x] create sample data for the database
- [x] save SQL script + sample data in Drive + resources project

**Example draft**
![image](https://app.gitkraken.com/api/glo/boards/5e303e1d9a4c6500104af4dc/attachments/5e404736757b7a00112b269e)

**Comment by EvilAngel94** [comment]
Sites which helped me realise I had to revite my design;
https://dev.to/amckean12/designing-a-relational-database-for-a-cookbook-4nj6

**Comment by EvilAngel94** [comment]
De link naar Amount classe zou weg moeten. Aangezien dit niet heel veel meerwaarde heeft.
