### ISSUE TITLE
Create a Jenkinsfile for the deployment

### ISSUE THREAD

**Issue by EvilAngel94** [EvilAngel94/RecipeCookBook#13]
**Description**
For the CI / CD pipeline, it would be nice to have a Jenkinsfile in the project, and have Jenkins read this file.

**TODO**
- [x] arrange Jenkins to be usable for this project
- [x] create the Jenkinsfile in the project
- [x] test if the Jenkinsfile works

**Jenkinsfile example**
[Jenkinsfile.txt](https://app.gitkraken.com/api/glo/boards/5e303e1d9a4c6500104af4dc/attachments/5e4a45e3a326a20010899fc1)

**Comment by EvilAngel94** [comment]
De Jenkinsfile.txt moet gewoon in je root folder zitten. 
----
Het Scriptpath moet je dan wel vanuit je project folder doen. Dus bijvoorbeeld: \jenkins\Jenkinsfile.txt
*\jenkins* is dan de naam van het project.
*\Jenkinsfile.txt* is de naam van de file die je dan wilt laten uitvoeren

**Comment by EvilAngel94** [comment]
Jenkins file is now working correctly.
