### ISSUE TITLE
Create the screen for displaying a recipe

### ISSUE THREAD

**Issue by EvilAngel94** [EvilAngel94/RecipeCookBook#8]
**Description**
Create the display for showing a recipe. The draft of the page can be found in underneath. There should be 3 buttons on top, going back to the main menu, go to the overview and create a new recipe.

**TODO**
- [x] create the html page
- [x] create the page view
- [x] use the same colour for the background as in the main page
- [x] test
- [x] document

**Example of the page**
![image](https://app.gitkraken.com/api/glo/boards/5e303e1d9a4c6500104af4dc/attachments/5e3f0976757b7a00112b0765)

**Comment by EvilAngel94** [comment]
Should dubblecheck if really the same colours are used as on the main page
